crudSimple/Models/EmpModel.cs
namespace crudSimple.Models
{
    public class EmpModel
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public int EmpSalary { get; set; }

    }
}

crudSimple/Models/ErrorViewModel.cs
namespace crudSimple.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

crudSimple/Controllers/EmpController.cs
using crudSimple.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Dapper;
using System.Data;
using NuGet.Protocol.Core.Types;

namespace crudSimple.Controllers
{
    public class EmpController : Controller
    {
        private readonly IConfiguration _Configuration;
        public EmpController(IConfiguration Configuration)
        {
            _Configuration = Configuration;
        }



        [HttpGet]

        public IActionResult getEmpList()
        {
            List<EmpModel> empList = new List<EmpModel>();
            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                empList = (List<EmpModel>)con.Query<EmpModel>("SPgetAllEmployees", commandType: CommandType.StoredProcedure);

            }
            return View(empList);
        }

        [HttpGet]
        public IActionResult getEmpByID()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Details(int id)
        {
            List<EmpModel> empList = new List<EmpModel>();
            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                DynamicParameters param = new DynamicParameters();
                param.Add("EmpID", id);
                empList = (List<EmpModel>)con.Query<EmpModel>("SPgetEmpByID", param, commandType: CommandType.StoredProcedure);

            }
            return View(empList);
        }

        public IActionResult Delete(int id)
        {
            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                DynamicParameters param = new DynamicParameters();
                param.Add("EmpID", id);
                con.Execute("SPemployeeDelete", param, commandType: CommandType.StoredProcedure);

            }
            return RedirectToAction("getEmpList");
        }



        [HttpGet]
        public IActionResult insertEmployee()
        {
            ModelState.Clear();
            return View();
        }

        [HttpPost]
        public IActionResult insertEmployee(EmpModel eMod)
        {
            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                var param = new
                {

                    EmpName = eMod.EmpName,
                    EmpEmail = eMod.EmpEmail,
                    EmpSalary = eMod.EmpSalary,
                };
                con.Execute("SPinsertEmp", param, commandType: CommandType.StoredProcedure);
            }
            ModelState.Clear();
            return View();
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            List<EmpModel> empList = new List<EmpModel>();
            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                DynamicParameters param = new DynamicParameters();
                param.Add("EmpID", id);
                EmpModel em = new EmpModel();
                using (SqlCommand command = new SqlCommand("SPgetEmpByID", con))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@EmpID", id);

                    // logic to read the data of the entered email id user and store it in the object of the model class
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            em.EmpID = (int)reader["EmpID"];
                            em.EmpName = reader["EmpName"].ToString();
                            em.EmpEmail = reader["EmpEmail"].ToString();
                            em.EmpSalary = (int)reader["EmpSalary"];
                        }
                    }

                }
                return View(em);
            }
        }

        [HttpPost]
        public IActionResult Update(EmpModel eMod)
        {
            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                DynamicParameters dp = new DynamicParameters();
                dp.Add("EmpID", eMod.EmpID);
                dp.Add("EmpName", eMod.EmpName);
                dp.Add("EmpEmail", eMod.EmpEmail);
                dp.Add("EmpSalary", eMod.EmpSalary);
                con.Execute("SPUpdateEmployee", dp, commandType: CommandType.StoredProcedure);
            }
            return RedirectToAction("getEmpList");
        }


        [HttpPost]
        public IActionResult InsertEmployee2(string EmpName, string EmpEmail, decimal EmpSalary)
        {

            using (SqlConnection con = new SqlConnection(_Configuration.GetConnectionString("DefaultConnection")))
            {
                con.Open();
                var param = new
                {

                    EmpName = EmpName,
                    EmpEmail = EmpEmail,
                    EmpSalary = EmpSalary,
                };
                con.Execute("SPinsertEmp", param, commandType: CommandType.StoredProcedure);
            }
            ModelState.Clear();
            return RedirectToAction("getEmpList");
        }
    }
}

crudSimple/Views/Emp/Details.cshtml
@model List<crudSimple.Models.EmpModel> 

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>


<h1>Employee List</h1>


<table class="table">
    <thead>
        <tr>
            <th>Employee ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Salary</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model)
        {
            <tr>
                <td>@emp.EmpID</td>
                <td>@emp.EmpName</td>
                <td>@emp.EmpEmail</td>
                <td>@emp.EmpSalary</td>

            </tr>

        }

    </tbody>
</table>

crudSimple/Views/Emp/Update.cshtml
@model crudSimple.Models.EmpModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update Employee</h1>

<h4>EmpModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" asp-controller="Emp" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none">
                <label asp-for="EmpID" class="control-label"></label>
                <input asp-for="EmpID" class="form-control" />
                <span asp-validation-for="EmpID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpName" class="control-label"></label>
                <input asp-for="EmpName" class="form-control" />
                <span asp-validation-for="EmpName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpEmail" class="control-label"></label>
                <input asp-for="EmpEmail" class="form-control" />
                <span asp-validation-for="EmpEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpSalary" class="control-label"></label>
                <input asp-for="EmpSalary" class="form-control" />
                <span asp-validation-for="EmpSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

crudSimple/Views/Emp/getEmpList.cshtml
@model List<crudSimple.Models.EmpModel>

@{
    ViewData["Title"] = "getEmpList";
}

<h1>Employee List</h1>


<table class="table">
    <thead>
        <tr>
            <th>Employee ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Salary</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model)
        {
            <tr>
                <td>@emp.EmpID</td>
                <td>@emp.EmpName</td>
                <td>@emp.EmpEmail</td>
                <td>@emp.EmpSalary</td>
                <td>
                    <form id="detailsForm" asp-controller="Emp" asp-action="Details" method="post">
                        <input type="hidden" name="id" value="@emp.EmpID" />
                        <button type="submit" class="link-button">Details</button>
                    </form>
                    <form id="detailsForm" asp-controller="Emp" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@emp.EmpID" />
                        <button type="submit" class="link-button">Delete</button>
                    </form>
                    <form id="detailsForm" asp-controller="Emp" asp-action="Update" method="get">
                        <input type="hidden" name="id" value="@emp.EmpID" />
                        <button type="submit" class="link-button">Update</button>
                    </form>
                </td>
            </tr>

        }

    </tbody>
</table>


<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

crudSimple/Views/Emp/insertEmployee.cshtml
@model crudSimple.Models.EmpModel

@{
    ViewData["Title"] = "insertEmployee";
}

<h1>insertEmployee</h1>

<h4>EmpModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="insertEmployee" asp-controller="Emp" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none">
                <label asp-for="EmpID" class="control-label"></label>
                <input asp-for="EmpID" class="form-control" />
                <span asp-validation-for="EmpID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpName" class="control-label"></label>
                <input asp-for="EmpName" id="en" class="form-control" />
                <span asp-validation-for="EmpName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpEmail" class="control-label"></label>
                <input asp-for="EmpEmail" id="ee" class="form-control" />
                <span asp-validation-for="EmpEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpSalary" class="control-label"></label>
                <input asp-for="EmpSalary" id="es" class="form-control" />
                <span asp-validation-for="EmpSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
        <div class="form-group">
            <input type="submit" value="Insert with Jquery" id="JQbtn" class="btn btn-primary" />
        </div>
    </div>
</div>


<div>
    <a asp-action="getEmpList" asp-controller="Emp" method="get">Get Employees List</a>
</div>

crudSimple/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

crudSimple/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - crudSimple</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/crudSimple.styles.css" asp-append-version="true" />
    <script src="~/js/site.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">crudSimple</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - crudSimple - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>